package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

var (
	flInput  = flag.String("in", "packets.json", "packets data report")
	flOutput = flag.String("out", "", "version name eg v772 for directory to be written to")
)

type protocol struct {
	Clientbound map[string]packet `json:"clientbound"`
	Serverbound map[string]packet `json:"serverbound"`
}

type packet struct {
	ProtocolID int `json:"protocol_id"`
}

type pk struct {
	name string
	id   int
}

func main() {
	flag.Parse()
	if *flOutput == "" {
		log.Fatal("output not set")
		return
	}

	log.Println("reading report json")
	var protos map[string]protocol
	must(json.Unmarshal(noerr(os.ReadFile(*flInput)), &protos))

	log.Printf("mkdir %q", *flOutput)
	must(os.MkdirAll(*flOutput, 0644))

	log.Printf("transforming")
	outpath := filepath.Join(*flOutput, "packetid.go")
	packageName := filepath.Base(*flOutput)
	buf := fmt.Sprintf("// Code generated by \"generators/packet.go\"; DO NOT EDIT.\n\npackage %s\n", packageName)
	buf += `
//go:generate stringer -type ClientboundPacketID
//go:generate stringer -type ServerboundPacketID
type (
	ClientboundPacketID int32
	ServerboundPacketID int32
)
`
	for protoName, packetsReport := range protos {
		protoNameTransformed := transformName(protoName)

		packets := []pk{}
		for packetName, packet := range packetsReport.Clientbound {
			packets = append(packets, pk{
				name: transformName(packetName),
				id:   packet.ProtocolID,
			})
		}
		sort.Slice(packets, func(i, j int) bool {
			return packets[i].id < packets[j].id
		})
		buf += "const (\n"
		for _, p := range packets {
			buf += fmt.Sprintf("\t%sClientbound%s = ClientboundPacketID(%d)\n", protoNameTransformed, p.name, p.id)
		}
		buf += ")\n\n"

		packets = []pk{}
		for packetName, packet := range packetsReport.Serverbound {
			packets = append(packets, pk{
				name: transformName(packetName),
				id:   packet.ProtocolID,
			})
		}
		sort.Slice(packets, func(i, j int) bool {
			return packets[i].id < packets[j].id
		})
		buf += "const (\n"
		for _, p := range packets {
			buf += fmt.Sprintf("\t%sServerbound%s = ServerboundPacketID(%d)\n", protoNameTransformed, p.name, p.id)
		}
		buf += ")\n\n"

	}

	log.Printf("writing %q", outpath)
	must(os.WriteFile(outpath, []byte(buf), 0644))
}

func transformName(mojoname string) string {
	words := strings.Split(strings.TrimPrefix(mojoname, "minecraft:"), "_")
	for i := range words {
		words[i] = toCapital(words[i])
	}
	return strings.Join(words, "")
}

func toCapital(word string) string {
	return strings.ToTitle(string(word[0])) + word[1:]
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}

func noerr[T any](ret T, err error) T {
	must(err)
	return ret
}
