// Code generated by "stringer -type ConfigurationServerboundPacketID"; DO NOT EDIT.

package v772

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConfigurationServerboundClientInformation-0]
	_ = x[ConfigurationServerboundCookieResponse-1]
	_ = x[ConfigurationServerboundCustomPayload-2]
	_ = x[ConfigurationServerboundFinishConfiguration-3]
	_ = x[ConfigurationServerboundKeepAlive-4]
	_ = x[ConfigurationServerboundPong-5]
	_ = x[ConfigurationServerboundResourcePack-6]
	_ = x[ConfigurationServerboundSelectKnownPacks-7]
	_ = x[ConfigurationServerboundCustomClickAction-8]
}

const _ConfigurationServerboundPacketID_name = "ConfigurationServerboundClientInformationConfigurationServerboundCookieResponseConfigurationServerboundCustomPayloadConfigurationServerboundFinishConfigurationConfigurationServerboundKeepAliveConfigurationServerboundPongConfigurationServerboundResourcePackConfigurationServerboundSelectKnownPacksConfigurationServerboundCustomClickAction"

var _ConfigurationServerboundPacketID_index = [...]uint16{0, 41, 79, 116, 159, 192, 220, 256, 296, 337}

func (i ConfigurationServerboundPacketID) String() string {
	if i < 0 || i >= ConfigurationServerboundPacketID(len(_ConfigurationServerboundPacketID_index)-1) {
		return "ConfigurationServerboundPacketID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConfigurationServerboundPacketID_name[_ConfigurationServerboundPacketID_index[i]:_ConfigurationServerboundPacketID_index[i+1]]
}
