// Code generated by "stringer -type ConfigurationClientboundPacketID"; DO NOT EDIT.

package v772

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConfigurationClientboundCookieRequest-0]
	_ = x[ConfigurationClientboundCustomPayload-1]
	_ = x[ConfigurationClientboundDisconnect-2]
	_ = x[ConfigurationClientboundFinishConfiguration-3]
	_ = x[ConfigurationClientboundKeepAlive-4]
	_ = x[ConfigurationClientboundPing-5]
	_ = x[ConfigurationClientboundResetChat-6]
	_ = x[ConfigurationClientboundRegistryData-7]
	_ = x[ConfigurationClientboundResourcePackPop-8]
	_ = x[ConfigurationClientboundResourcePackPush-9]
	_ = x[ConfigurationClientboundStoreCookie-10]
	_ = x[ConfigurationClientboundTransfer-11]
	_ = x[ConfigurationClientboundUpdateEnabledFeatures-12]
	_ = x[ConfigurationClientboundUpdateTags-13]
	_ = x[ConfigurationClientboundSelectKnownPacks-14]
	_ = x[ConfigurationClientboundCustomReportDetails-15]
	_ = x[ConfigurationClientboundServerLinks-16]
	_ = x[ConfigurationClientboundClearDialog-17]
	_ = x[ConfigurationClientboundShowDialog-18]
}

const _ConfigurationClientboundPacketID_name = "ConfigurationClientboundCookieRequestConfigurationClientboundCustomPayloadConfigurationClientboundDisconnectConfigurationClientboundFinishConfigurationConfigurationClientboundKeepAliveConfigurationClientboundPingConfigurationClientboundResetChatConfigurationClientboundRegistryDataConfigurationClientboundResourcePackPopConfigurationClientboundResourcePackPushConfigurationClientboundStoreCookieConfigurationClientboundTransferConfigurationClientboundUpdateEnabledFeaturesConfigurationClientboundUpdateTagsConfigurationClientboundSelectKnownPacksConfigurationClientboundCustomReportDetailsConfigurationClientboundServerLinksConfigurationClientboundClearDialogConfigurationClientboundShowDialog"

var _ConfigurationClientboundPacketID_index = [...]uint16{0, 37, 74, 108, 151, 184, 212, 245, 281, 320, 360, 395, 427, 472, 506, 546, 589, 624, 659, 693}

func (i ConfigurationClientboundPacketID) String() string {
	if i < 0 || i >= ConfigurationClientboundPacketID(len(_ConfigurationClientboundPacketID_index)-1) {
		return "ConfigurationClientboundPacketID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConfigurationClientboundPacketID_name[_ConfigurationClientboundPacketID_index[i]:_ConfigurationClientboundPacketID_index[i+1]]
}
