// Code generated by "stringer -type HandshakeServerboundPacketID"; DO NOT EDIT.

package v772

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HandshakeServerboundIntention-0]
}

const _HandshakeServerboundPacketID_name = "HandshakeServerboundIntention"

var _HandshakeServerboundPacketID_index = [...]uint8{0, 29}

func (i HandshakeServerboundPacketID) String() string {
	if i < 0 || i >= HandshakeServerboundPacketID(len(_HandshakeServerboundPacketID_index)-1) {
		return "HandshakeServerboundPacketID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HandshakeServerboundPacketID_name[_HandshakeServerboundPacketID_index[i]:_HandshakeServerboundPacketID_index[i+1]]
}
