// Code generated by "stringer -type LoginServerboundPacketID"; DO NOT EDIT.

package v772

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LoginServerboundHello-0]
	_ = x[LoginServerboundKey-1]
	_ = x[LoginServerboundCustomQueryAnswer-2]
	_ = x[LoginServerboundLoginAcknowledged-3]
	_ = x[LoginServerboundCookieResponse-4]
}

const _LoginServerboundPacketID_name = "LoginServerboundHelloLoginServerboundKeyLoginServerboundCustomQueryAnswerLoginServerboundLoginAcknowledgedLoginServerboundCookieResponse"

var _LoginServerboundPacketID_index = [...]uint8{0, 21, 40, 73, 106, 136}

func (i LoginServerboundPacketID) String() string {
	if i < 0 || i >= LoginServerboundPacketID(len(_LoginServerboundPacketID_index)-1) {
		return "LoginServerboundPacketID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LoginServerboundPacketID_name[_LoginServerboundPacketID_index[i]:_LoginServerboundPacketID_index[i+1]]
}
