// Code generated by "stringer -type LoginClientboundPacketID"; DO NOT EDIT.

package v772

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LoginClientboundLoginDisconnect-0]
	_ = x[LoginClientboundHello-1]
	_ = x[LoginClientboundLoginFinished-2]
	_ = x[LoginClientboundLoginCompression-3]
	_ = x[LoginClientboundCustomQuery-4]
	_ = x[LoginClientboundCookieRequest-5]
}

const _LoginClientboundPacketID_name = "LoginClientboundLoginDisconnectLoginClientboundHelloLoginClientboundLoginFinishedLoginClientboundLoginCompressionLoginClientboundCustomQueryLoginClientboundCookieRequest"

var _LoginClientboundPacketID_index = [...]uint8{0, 31, 52, 81, 113, 140, 169}

func (i LoginClientboundPacketID) String() string {
	if i < 0 || i >= LoginClientboundPacketID(len(_LoginClientboundPacketID_index)-1) {
		return "LoginClientboundPacketID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LoginClientboundPacketID_name[_LoginClientboundPacketID_index[i]:_LoginClientboundPacketID_index[i+1]]
}
