// Code generated by "stringer -type PlayServerboundPacketID"; DO NOT EDIT.

package v772

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PlayServerboundAcceptTeleportation-0]
	_ = x[PlayServerboundBlockEntityTagQuery-1]
	_ = x[PlayServerboundBundleItemSelected-2]
	_ = x[PlayServerboundChangeDifficulty-3]
	_ = x[PlayServerboundChangeGameMode-4]
	_ = x[PlayServerboundChatAck-5]
	_ = x[PlayServerboundChatCommand-6]
	_ = x[PlayServerboundChatCommandSigned-7]
	_ = x[PlayServerboundChat-8]
	_ = x[PlayServerboundChatSessionUpdate-9]
	_ = x[PlayServerboundChunkBatchReceived-10]
	_ = x[PlayServerboundClientCommand-11]
	_ = x[PlayServerboundClientTickEnd-12]
	_ = x[PlayServerboundClientInformation-13]
	_ = x[PlayServerboundCommandSuggestion-14]
	_ = x[PlayServerboundConfigurationAcknowledged-15]
	_ = x[PlayServerboundContainerButtonClick-16]
	_ = x[PlayServerboundContainerClick-17]
	_ = x[PlayServerboundContainerClose-18]
	_ = x[PlayServerboundContainerSlotStateChanged-19]
	_ = x[PlayServerboundCookieResponse-20]
	_ = x[PlayServerboundCustomPayload-21]
	_ = x[PlayServerboundDebugSampleSubscription-22]
	_ = x[PlayServerboundEditBook-23]
	_ = x[PlayServerboundEntityTagQuery-24]
	_ = x[PlayServerboundInteract-25]
	_ = x[PlayServerboundJigsawGenerate-26]
	_ = x[PlayServerboundKeepAlive-27]
	_ = x[PlayServerboundLockDifficulty-28]
	_ = x[PlayServerboundMovePlayerPos-29]
	_ = x[PlayServerboundMovePlayerPosRot-30]
	_ = x[PlayServerboundMovePlayerRot-31]
	_ = x[PlayServerboundMovePlayerStatusOnly-32]
	_ = x[PlayServerboundMoveVehicle-33]
	_ = x[PlayServerboundPaddleBoat-34]
	_ = x[PlayServerboundPickItemFromBlock-35]
	_ = x[PlayServerboundPickItemFromEntity-36]
	_ = x[PlayServerboundPingRequest-37]
	_ = x[PlayServerboundPlaceRecipe-38]
	_ = x[PlayServerboundPlayerAbilities-39]
	_ = x[PlayServerboundPlayerAction-40]
	_ = x[PlayServerboundPlayerCommand-41]
	_ = x[PlayServerboundPlayerInput-42]
	_ = x[PlayServerboundPlayerLoaded-43]
	_ = x[PlayServerboundPong-44]
	_ = x[PlayServerboundRecipeBookChangeSettings-45]
	_ = x[PlayServerboundRecipeBookSeenRecipe-46]
	_ = x[PlayServerboundRenameItem-47]
	_ = x[PlayServerboundResourcePack-48]
	_ = x[PlayServerboundSeenAdvancements-49]
	_ = x[PlayServerboundSelectTrade-50]
	_ = x[PlayServerboundSetBeacon-51]
	_ = x[PlayServerboundSetCarriedItem-52]
	_ = x[PlayServerboundSetCommandBlock-53]
	_ = x[PlayServerboundSetCommandMinecart-54]
	_ = x[PlayServerboundSetCreativeModeSlot-55]
	_ = x[PlayServerboundSetJigsawBlock-56]
	_ = x[PlayServerboundSetStructureBlock-57]
	_ = x[PlayServerboundSetTestBlock-58]
	_ = x[PlayServerboundSignUpdate-59]
	_ = x[PlayServerboundSwing-60]
	_ = x[PlayServerboundTeleportToEntity-61]
	_ = x[PlayServerboundTestInstanceBlockAction-62]
	_ = x[PlayServerboundUseItemOn-63]
	_ = x[PlayServerboundUseItem-64]
	_ = x[PlayServerboundCustomClickAction-65]
}

const _PlayServerboundPacketID_name = "PlayServerboundAcceptTeleportationPlayServerboundBlockEntityTagQueryPlayServerboundBundleItemSelectedPlayServerboundChangeDifficultyPlayServerboundChangeGameModePlayServerboundChatAckPlayServerboundChatCommandPlayServerboundChatCommandSignedPlayServerboundChatPlayServerboundChatSessionUpdatePlayServerboundChunkBatchReceivedPlayServerboundClientCommandPlayServerboundClientTickEndPlayServerboundClientInformationPlayServerboundCommandSuggestionPlayServerboundConfigurationAcknowledgedPlayServerboundContainerButtonClickPlayServerboundContainerClickPlayServerboundContainerClosePlayServerboundContainerSlotStateChangedPlayServerboundCookieResponsePlayServerboundCustomPayloadPlayServerboundDebugSampleSubscriptionPlayServerboundEditBookPlayServerboundEntityTagQueryPlayServerboundInteractPlayServerboundJigsawGeneratePlayServerboundKeepAlivePlayServerboundLockDifficultyPlayServerboundMovePlayerPosPlayServerboundMovePlayerPosRotPlayServerboundMovePlayerRotPlayServerboundMovePlayerStatusOnlyPlayServerboundMoveVehiclePlayServerboundPaddleBoatPlayServerboundPickItemFromBlockPlayServerboundPickItemFromEntityPlayServerboundPingRequestPlayServerboundPlaceRecipePlayServerboundPlayerAbilitiesPlayServerboundPlayerActionPlayServerboundPlayerCommandPlayServerboundPlayerInputPlayServerboundPlayerLoadedPlayServerboundPongPlayServerboundRecipeBookChangeSettingsPlayServerboundRecipeBookSeenRecipePlayServerboundRenameItemPlayServerboundResourcePackPlayServerboundSeenAdvancementsPlayServerboundSelectTradePlayServerboundSetBeaconPlayServerboundSetCarriedItemPlayServerboundSetCommandBlockPlayServerboundSetCommandMinecartPlayServerboundSetCreativeModeSlotPlayServerboundSetJigsawBlockPlayServerboundSetStructureBlockPlayServerboundSetTestBlockPlayServerboundSignUpdatePlayServerboundSwingPlayServerboundTeleportToEntityPlayServerboundTestInstanceBlockActionPlayServerboundUseItemOnPlayServerboundUseItemPlayServerboundCustomClickAction"

var _PlayServerboundPacketID_index = [...]uint16{0, 34, 68, 101, 132, 161, 183, 209, 241, 260, 292, 325, 353, 381, 413, 445, 485, 520, 549, 578, 618, 647, 675, 713, 736, 765, 788, 817, 841, 870, 898, 929, 957, 992, 1018, 1043, 1075, 1108, 1134, 1160, 1190, 1217, 1245, 1271, 1298, 1317, 1356, 1391, 1416, 1443, 1474, 1500, 1524, 1553, 1583, 1616, 1650, 1679, 1711, 1738, 1763, 1783, 1814, 1852, 1876, 1898, 1930}

func (i PlayServerboundPacketID) String() string {
	if i < 0 || i >= PlayServerboundPacketID(len(_PlayServerboundPacketID_index)-1) {
		return "PlayServerboundPacketID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PlayServerboundPacketID_name[_PlayServerboundPacketID_index[i]:_PlayServerboundPacketID_index[i+1]]
}
