// Code generated by "stringer -type StatusClientboundPacketID"; DO NOT EDIT.

package v772

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusClientboundStatusResponse-0]
	_ = x[StatusClientboundPongResponse-1]
}

const _StatusClientboundPacketID_name = "StatusClientboundStatusResponseStatusClientboundPongResponse"

var _StatusClientboundPacketID_index = [...]uint8{0, 31, 60}

func (i StatusClientboundPacketID) String() string {
	if i < 0 || i >= StatusClientboundPacketID(len(_StatusClientboundPacketID_index)-1) {
		return "StatusClientboundPacketID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StatusClientboundPacketID_name[_StatusClientboundPacketID_index[i]:_StatusClientboundPacketID_index[i+1]]
}
