// Code generated by "stringer -type StatusServerboundPacketID"; DO NOT EDIT.

package v772

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusServerboundStatusRequest-0]
	_ = x[StatusServerboundPingRequest-1]
}

const _StatusServerboundPacketID_name = "StatusServerboundStatusRequestStatusServerboundPingRequest"

var _StatusServerboundPacketID_index = [...]uint8{0, 30, 58}

func (i StatusServerboundPacketID) String() string {
	if i < 0 || i >= StatusServerboundPacketID(len(_StatusServerboundPacketID_index)-1) {
		return "StatusServerboundPacketID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StatusServerboundPacketID_name[_StatusServerboundPacketID_index[i]:_StatusServerboundPacketID_index[i+1]]
}
